environment:
  type: corridor
  corridor_length: 12.0
  corridor_width: 3.0
  wall_A: 5.0
  wall_B: 0.3
  absorbing_boundary: true  # Set to true to remove agents at corridor ends

agents:
  num_per_group: 100
  walking_speed: 1.3

physics:
  k: 1.5
  m: 2.0
  t0: 3
  rad: 0.2
  sight: 7
  maxF: 5
  dt: 0.02
