width: 200
height: 300

entrance:
 - type: line
   start: [0, 6]
   end: [0, 8]
 - type: line
   start: [0, 12]
   end: [0, 14]
 - type: line
   start: [0, 18]
   end: [0, 20]
 - type: line
   start: [0, 24]
   end: [0, 26]
 - type: line
   start: [0, 30]
   end: [0, 32]
 - type: line
   start: [0, 36]
   end: [0, 38]
 - type: line
   start: [0, 42]
   end: [0, 44]
 - type: line
   start: [0, 48]
   end: [0, 50]
 - type: line
   start: [0, 54]
   end: [0, 56]
 - type: line
   start: [0, 60]
   end: [0, 62]
 - type: line
   start: [0, 66]
   end: [0, 68]
 - type: line
   start: [0, 72]
   end: [0, 74]
 - type: line
   start: [0, 78]
   end: [0, 80]
 - type: line
   start: [0, 84]
   end: [0, 86]
 - type: line
   start: [0, 90]
   end: [0, 92]
 - type: line
   start: [0, 96]
   end: [0, 98]
 - type: line
   start: [0, 102]
   end: [0, 104]
 - type: line
   start: [0, 108]
   end: [0, 110]
 - type: line
   start: [0, 114]
   end: [0, 116]
 - type: line
   start: [0, 120]
   end: [0, 122]
 - type: line
   start: [0, 126]
   end: [0, 128]
 - type: line
   start: [0, 132]
   end: [0, 134]
 - type: line
   start: [0, 138]
   end: [0, 140]
 - type: line
   start: [0, 144]
   end: [0, 146]
 - type: line
   start: [0, 150]
   end: [0, 152]
 - type: line
   start: [0, 156]
   end: [0, 158]
 - type: line
   start: [0, 162]
   end: [0, 164]
 - type: line
   start: [0, 168]
   end: [0, 170]
 - type: line
   start: [0, 174]
   end: [0, 176]
 - type: line
   start: [0, 180]
   end: [0, 182]
 - type: line
   start: [0, 186]
   end: [0, 188]
 - type: line
   start: [0, 192]
   end: [0, 194]
 - type: line
   start: [0, 198]
   end: [0, 200]
 - type: line
   start: [0, 204]
   end: [0, 206]
 - type: line
   start: [0, 210]
   end: [0, 212]
 - type: line
   start: [0, 216]
   end: [0, 218]
 - type: line
   start: [0, 222]
   end: [0, 224]
 - type: line
   start: [0, 228]
   end: [0, 230]
 - type: line
   start: [0, 234]
   end: [0, 236]
 - type: line
   start: [0, 240]
   end: [0, 242]
 - type: line
   start: [0, 246]
   end: [0, 248]
 - type: line
   start: [0, 252]
   end: [0, 254]
 - type: line
   start: [0, 258]
   end: [0, 260]
 - type: line
   start: [0, 264]
   end: [0, 266]
 - type: line
   start: [0, 270]
   end: [0, 272]
 - type: line
   start: [0, 276]
   end: [0, 278]
 - type: line
   start: [0, 282]
   end: [0, 284]
 - type: line
   start: [0, 288]
   end: [0, 290]
 - type: line
   start: [199, 6]
   end: [199, 8]
 - type: line
   start: [199, 12]
   end: [199, 14]
 - type: line
   start: [199, 18]
   end: [199, 20]
 - type: line
   start: [199, 24]
   end: [199, 26]
 - type: line
   start: [199, 30]
   end: [199, 32]
 - type: line
   start: [199, 36]
   end: [199, 38]
 - type: line
   start: [199, 42]
   end: [199, 44]
 - type: line
   start: [199, 48]
   end: [199, 50]
 - type: line
   start: [199, 54]
   end: [199, 56]
 - type: line
   start: [199, 60]
   end: [199, 62]
 - type: line
   start: [199, 66]
   end: [199, 68]
 - type: line
   start: [199, 72]
   end: [199, 74]
 - type: line
   start: [199, 78]
   end: [199, 80]
 - type: line
   start: [199, 84]
   end: [199, 86]
 - type: line
   start: [199, 90]
   end: [199, 92]
 - type: line
   start: [199, 96]
   end: [199, 98]
 - type: line
   start: [199, 102]
   end: [199, 104]
 - type: line
   start: [199, 108]
   end: [199, 110]
 - type: line
   start: [199, 114]
   end: [199, 116]
 - type: line
   start: [199, 120]
   end: [199, 122]
 - type: line
   start: [199, 126]
   end: [199, 128]
 - type: line
   start: [199, 132]
   end: [199, 134]
 - type: line
   start: [199, 138]
   end: [199, 140]
 - type: line
   start: [199, 144]
   end: [199, 146]
 - type: line
   start: [199, 150]
   end: [199, 152]
 - type: line
   start: [199, 156]
   end: [199, 158]
 - type: line
   start: [199, 162]
   end: [199, 164]
 - type: line
   start: [199, 168]
   end: [199, 170]
 - type: line
   start: [199, 174]
   end: [199, 176]
 - type: line
   start: [199, 180]
   end: [199, 182]
 - type: line
   start: [199, 186]
   end: [199, 188]
 - type: line
   start: [199, 192]
   end: [199, 194]
 - type: line
   start: [199, 198]
   end: [199, 200]
 - type: line
   start: [199, 204]
   end: [199, 206]
 - type: line
   start: [199, 210]
   end: [199, 212]
 - type: line
   start: [199, 216]
   end: [199, 218]
 - type: line
   start: [199, 222]
   end: [199, 224]
 - type: line
   start: [199, 228]
   end: [199, 230]
 - type: line
   start: [199, 234]
   end: [199, 236]
 - type: line
   start: [199, 240]
   end: [199, 242]
 - type: line
   start: [199, 246]
   end: [199, 248]
 - type: line
   start: [199, 252]
   end: [199, 254]
 - type: line
   start: [199, 258]
   end: [199, 260]
 - type: line
   start: [199, 264]
   end: [199, 266]
 - type: line
   start: [199, 270]
   end: [199, 272]
 - type: line
   start: [199, 276]
   end: [199, 278]
 - type: line
   start: [199, 282]
   end: [199, 284]
 - type: line
   start: [199, 288]
   end: [199, 290]

exit:
 - type: line
   start: [0, 9]
   end: [0, 11]
 - type: line
   start: [0, 15]
   end: [0, 17]
 - type: line
   start: [0, 21]
   end: [0, 23]
 - type: line
   start: [0, 27]
   end: [0, 29]
 - type: line
   start: [0, 33]
   end: [0, 35]
 - type: line
   start: [0, 39]
   end: [0, 41]
 - type: line
   start: [0, 45]
   end: [0, 47]
 - type: line
   start: [0, 51]
   end: [0, 53]
 - type: line
   start: [0, 57]
   end: [0, 59]
 - type: line
   start: [0, 63]
   end: [0, 65]
 - type: line
   start: [0, 69]
   end: [0, 71]
 - type: line
   start: [0, 75]
   end: [0, 77]
 - type: line
   start: [0, 81]
   end: [0, 83]
 - type: line
   start: [0, 87]
   end: [0, 89]
 - type: line
   start: [0, 93]
   end: [0, 95]
 - type: line
   start: [0, 99]
   end: [0, 101]
 - type: line
   start: [0, 105]
   end: [0, 107]
 - type: line
   start: [0, 111]
   end: [0, 113]
 - type: line
   start: [0, 117]
   end: [0, 119]
 - type: line
   start: [0, 123]
   end: [0, 125]
 - type: line
   start: [0, 129]
   end: [0, 131]
 - type: line
   start: [0, 135]
   end: [0, 137]
 - type: line
   start: [0, 141]
   end: [0, 143]
 - type: line
   start: [0, 147]
   end: [0, 149]
 - type: line
   start: [0, 153]
   end: [0, 155]
 - type: line
   start: [0, 159]
   end: [0, 161]
 - type: line
   start: [0, 165]
   end: [0, 167]
 - type: line
   start: [0, 171]
   end: [0, 173]
 - type: line
   start: [0, 177]
   end: [0, 179]
 - type: line
   start: [0, 183]
   end: [0, 185]
 - type: line
   start: [0, 189]
   end: [0, 191]
 - type: line
   start: [0, 195]
   end: [0, 197]
 - type: line
   start: [0, 201]
   end: [0, 203]
 - type: line
   start: [0, 207]
   end: [0, 209]
 - type: line
   start: [0, 213]
   end: [0, 215]
 - type: line
   start: [0, 219]
   end: [0, 221]
 - type: line
   start: [0, 225]
   end: [0, 227]
 - type: line
   start: [0, 231]
   end: [0, 233]
 - type: line
   start: [0, 237]
   end: [0, 239]
 - type: line
   start: [0, 243]
   end: [0, 245]
 - type: line
   start: [0, 249]
   end: [0, 251]
 - type: line
   start: [0, 255]
   end: [0, 257]
 - type: line
   start: [0, 261]
   end: [0, 263]
 - type: line
   start: [0, 267]
   end: [0, 269]
 - type: line
   start: [0, 273]
   end: [0, 275]
 - type: line
   start: [0, 279]
   end: [0, 281]
 - type: line
   start: [0, 285]
   end: [0, 287]
 - type: line
   start: [0, 291]
   end: [0, 293]
 - type: line
   start: [199, 9]
   end: [199, 11]
 - type: line
   start: [199, 15]
   end: [199, 17]
 - type: line
   start: [199, 21]
   end: [199, 23]
 - type: line
   start: [199, 27]
   end: [199, 29]
 - type: line
   start: [199, 33]
   end: [199, 35]
 - type: line
   start: [199, 39]
   end: [199, 41]
 - type: line
   start: [199, 45]
   end: [199, 47]
 - type: line
   start: [199, 51]
   end: [199, 53]
 - type: line
   start: [199, 57]
   end: [199, 59]
 - type: line
   start: [199, 63]
   end: [199, 65]
 - type: line
   start: [199, 69]
   end: [199, 71]
 - type: line
   start: [199, 75]
   end: [199, 77]
 - type: line
   start: [199, 81]
   end: [199, 83]
 - type: line
   start: [199, 87]
   end: [199, 89]
 - type: line
   start: [199, 93]
   end: [199, 95]
 - type: line
   start: [199, 99]
   end: [199, 101]
 - type: line
   start: [199, 105]
   end: [199, 107]
 - type: line
   start: [199, 111]
   end: [199, 113]
 - type: line
   start: [199, 117]
   end: [199, 119]
 - type: line
   start: [199, 123]
   end: [199, 125]
 - type: line
   start: [199, 129]
   end: [199, 131]
 - type: line
   start: [199, 135]
   end: [199, 137]
 - type: line
   start: [199, 141]
   end: [199, 143]
 - type: line
   start: [199, 147]
   end: [199, 149]
 - type: line
   start: [199, 153]
   end: [199, 155]
 - type: line
   start: [199, 159]
   end: [199, 161]
 - type: line
   start: [199, 165]
   end: [199, 167]
 - type: line
   start: [199, 171]
   end: [199, 173]
 - type: line
   start: [199, 177]
   end: [199, 179]
 - type: line
   start: [199, 183]
   end: [199, 185]
 - type: line
   start: [199, 189]
   end: [199, 191]
 - type: line
   start: [199, 195]
   end: [199, 197]
 - type: line
   start: [199, 201]
   end: [199, 203]
 - type: line
   start: [199, 207]
   end: [199, 209]
 - type: line
   start: [199, 213]
   end: [199, 215]
 - type: line
   start: [199, 219]
   end: [199, 221]
 - type: line
   start: [199, 225]
   end: [199, 227]
 - type: line
   start: [199, 231]
   end: [199, 233]
 - type: line
   start: [199, 237]
   end: [199, 239]
 - type: line
   start: [199, 243]
   end: [199, 245]
 - type: line
   start: [199, 249]
   end: [199, 251]
 - type: line
   start: [199, 255]
   end: [199, 257]
 - type: line
   start: [199, 261]
   end: [199, 263]
 - type: line
   start: [199, 267]
   end: [199, 269]
 - type: line
   start: [199, 273]
   end: [199, 275]
 - type: line
   start: [199, 279]
   end: [199, 281]
 - type: line
   start: [199, 285]
   end: [199, 287]
 - type: line
   start: [199, 291]
   end: [199, 293]